### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by mam4dali** [hylander0/Iteedee.ApkReader#18]
hi,
I have this problem on large files!
I tested this with: instagram last version ( 38MB )
This problem does not exist in small files. Only big files like that

Error Message:
> Unhandled Exception: System.Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Iteedee.ApkReader.APKManifest.LEW(Byte[] arr, Int32 off) in Iteedee.ApkReader\APKManifest.cs:line 248
   at Iteedee.ApkReader.APKManifest.ReadManifestFileIntoXml(Byte[] manifestFileData) in Iteedee.ApkReader\APKManifest.cs:line 104
   at Iteedee.ApkReader.ApkReader.extractInfo(Byte[] manifest_xml, Byte[] resources_arsx) in Iteedee.ApkReader\ApkReader.cs:line 99
   at Iteedee.ApkReader.ApkReader.extractInfo(Byte[] manifest_xml, Byte[] resources_arsx) in Iteedee.ApkReader\ApkReader.cs:line 103
   at Iteedee.ApkReader.Run.ReadApk.ReadApkFromPath(String path) in Iteedee.ApkReader.Run\ReadApk.cs:line 49
   at Iteedee.ApkReader.Run.Program.Main(String[] args) in Iteedee.ApkReader.Run\Program.cs:line 16

line 248 in "APKManifest.cs":
`return (int)(((uint)arr[off + 3]) << 24 & 0xff000000 | ((uint)arr[off + 2]) << 16 & 0xff0000 | ((uint)arr[off + 1]) << 8 & 0xff00 | ((uint)arr[off]) & 0xFF);`
in:
`public int LEW(byte[] arr, int off)`

**Comment by yurik94** [comment]
same here (Chrome APK 72) about 120 MB

**Comment by SudhuMe** [comment]
Same issue, fails with apps above 10mb at times.
Is there any fix for it?

**Comment by viraln25** [comment]
Facing same issue. Is there any fix for it yet?
